PiekShop/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PiekShop.Models;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    //Only support one type of currency so good practice there would be an creating an money/currency object :)
    [Column(TypeName = "decimal(6, 2)")]
    public decimal Price { get; set; }
    public bool IsActive { get; set; } = true;
    public virtual List<BasketProducts> Baskets { get; set; } = new List<BasketProducts>();
}

PiekShop/Controllers/ProductsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PiekShop.Data;
using PiekShop.Models;
using PiekShop.Models.Enums;

namespace PiekShop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ProductsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.Where(x => x.IsActive).ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id && m.IsActive);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int productId, int amount)
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User);
            var activeBasket = await _context.Baskets.SingleOrDefaultAsync(x =>
                x.StateOfTransaction == StateOfTransaction.Started && x.UserId == currentUserId);

            var basketProduct = await
                _context.BasketProducts.SingleOrDefaultAsync(x => x.BasketId == activeBasket.Id && x.ProductId == productId);

            if (basketProduct != null)
            {
                basketProduct.Amount += amount;
            }
            else
            {
                var productInBasket = new BasketProducts()
                    { Amount = amount, BasketId = activeBasket.Id, ProductId = productId };
                _context.Add(productInBasket);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

PiekShop/Views/Products/Details.cshtml
@model PiekShop.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> | *@
    <a asp-action="Index">Back to List</a>
</div>

PiekShop/Views/Products/Index.cshtml
@model IEnumerable<PiekShop.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    @using (Html.BeginForm("Add", "Products"))
    {
        <input type="text" name="productId" value="@item.Id" style="display: none;"/>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <input type="number" name="amount" value="1"/>
            </td>
            <td>
                <input type = "submit" value="Add"/>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
    }
}
    </tbody>
</table>